config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'

  namespace :admin do
    resources :users
    resources :items
    resources :item_types
    resources :reservations
    resources :schools

    root to: "users#index"
  end

  resources :reservations do
    resources :items
    resources :users
  end
  resources :items do
    collection do
      get 'search'
    end
    resources :reservations
  end
  resources :item_types
  resources :schools
  devise_for :users, :controllers => { registrations: 'registrations' }

end

app/controllers/admin/item_types_controller.rb
module Admin
  class ItemTypesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = ItemType.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   ItemType.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/item_types_controller.rb
class ItemTypesController < ApplicationController
  before_action :set_item_type, only: [:show, :edit, :update, :destroy]

  # GET /item_types
  # GET /item_types.json
  def index
    @item_types = ItemType.all
  end

  # GET /item_types/1
  # GET /item_types/1.json
  def show
  end

  # GET /item_types/new
  def new
    @item_type = ItemType.new
  end

  # GET /item_types/1/edit
  def edit
  end

  # POST /item_types
  # POST /item_types.json
  def create
    @item_type = ItemType.new(item_type_params)

    respond_to do |format|
      if @item_type.save
        format.html { redirect_to @item_type, notice: 'Item type was successfully created.' }
        format.json { render :show, status: :created, location: @item_type }
      else
        format.html { render :new }
        format.json { render json: @item_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_types/1
  # PATCH/PUT /item_types/1.json
  def update
    respond_to do |format|
      if @item_type.update(item_type_params)
        format.html { redirect_to @item_type, notice: 'Item type was successfully updated.' }
        format.json { render :show, status: :ok, location: @item_type }
      else
        format.html { render :edit }
        format.json { render json: @item_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_types/1
  # DELETE /item_types/1.json
  def destroy
    @item_type.destroy
    respond_to do |format|
      format.html { redirect_to item_types_url, notice: 'Item type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_type
      @item_type = ItemType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_type_params
      params.require(:item_type).permit(:name)
    end
end

app/helpers/item_types_helper.rb
module ItemTypesHelper
end

app/views/item_types/_form.html.erb
<%= form_for(@item_type) do |f| %>
  <% if @item_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item_type.errors.count, "error") %> prohibited this item_type from being saved:</h2>

      <ul>
      <% @item_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/item_types/edit.html.erb
<h1>Editing Item Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @item_type %> |
<%= link_to 'Back', item_types_path %>

app/views/item_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Item Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @item_types.each do |item_type| %>
      <tr>
        <td><%= item_type.name %></td>
        <td><%= link_to 'Show', item_type %></td>
        <td><%= link_to 'Edit', edit_item_type_path(item_type) %></td>
        <td><%= link_to 'Destroy', item_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item type', new_item_type_path %>

app/views/item_types/new.html.erb
<h1>New Item Type</h1>

<%= render 'form' %>

<%= link_to 'Back', item_types_path %>

app/views/item_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item_type.name %>
</p>

<%= link_to 'Edit', edit_item_type_path(@item_type) %> |
<%= link_to 'Back', item_types_path %>