config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'

  namespace :admin do
    resources :users
    resources :items
    resources :item_types
    resources :reservations
    resources :schools

    root to: "users#index"
  end

  resources :reservations do
    resources :items
    resources :users
  end
  resources :items do
    collection do
      get 'search'
    end
    resources :reservations
  end
  resources :item_types
  resources :schools
  devise_for :users, :controllers => { registrations: 'registrations' }

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  belongs_to :item_type
  has_many :reservations, dependent: :destroy
  searchkick searchable: [:name, :description, :user]

  def available
    self.reservations.each() do |r|
      if not r.returned
        return false
      end
    end
    return true
  end
end

app/models/item_type.rb
class ItemType < ActiveRecord::Base
  has_many :items, dependent: :destroy
end

app/controllers/admin/items_controller.rb
module Admin
  class ItemsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Item.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Item.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_filter :require_permission, only: :edit

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  def search
    @items = Item.search params[:search]
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  def require_permission
    if current_user.id != Item.find(params[:id]).user
      redirect_to root_path
      #Or do something else here
    end
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:description, :user_id, :item_type_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= simple_form_for(@item) do |f| %>
    <% if @item.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

          <ul>
            <% @item.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :user_id, as: :hidden, :input_html => {:value => current_user.id} %>
    <%= f.association :item_type, as: :select %>
    <%= f.submit %>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Available Items</h1>
<tbody>
<% @items.each do |item| %>
    <div class="panel panel-default">
      <div class ="panel-heading">
        <%= item.description %> <br>
      </div>
      <div class="panel-body">
        Owned by <%= item.user.name %> at
        <%= item.user.school.name %> <br>
        <%= item.item_type.name %> <br>
        <%= item.name %> <br>
        <br>
        <%= link_to 'Show', item %> <br>
        <% if user_signed_in? %>
            <%= link_to 'Reserve Now!', new_reservation_path(:curr_item => item.id, :item_name => item.name) %>
        <% else %>
            <%= link_to 'Sign up now to reserve!', '/users/sign_in', class: "btn-default" %>
        <% end %>

      </div>
    </div>
<% end %>
</tbody>

<br>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/search.html.erb
<% @items.each do |item| %>
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="text">
          <%= link_to item.name, items_path(item, :search_id => @search_id) %> <br>
          <%= item.item_type.name %>
        </div>
      </div>
    </div>
<% end %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @item.user.name %>
</p>

<p>
  <strong>Item type:</strong>
  <%= @item.item_type.name %>
</p>

<p>
  <strong>Times borrowed:</strong>
  <%= @item.times_borrowed %>
</p>

<p>
  <strong>Item type:</strong>
  <%= @item.id %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>