config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'

  namespace :admin do
    resources :users
    resources :items
    resources :item_types
    resources :reservations
    resources :schools

    root to: "users#index"
  end

  resources :reservations do
    resources :items
    resources :users
  end
  resources :items do
    collection do
      get 'search'
    end
    resources :reservations
  end
  resources :item_types
  resources :schools
  devise_for :users, :controllers => { registrations: 'registrations' }

end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
        <i class="fa fa-bars"></i>
      </button>
      <a class="navbar-brand page-scroll" href="/">
        Lendy
      </a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
      <ul class="nav navbar-nav">
        <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
        <li class="hidden">
          <a href="#page-top"></a>
        </li>
        <li>
        <%= form_tag search_items_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
            <p>
              <%= text_field_tag :search, params[:search], class: "form-control" %>
              <%= submit_tag "Search", name: nil, class: "btn btn-primary" %>
            </p>
        <% end %>
        </li>
        <li>
          <a class="page-scroll" href="admin">Admin</a>
        </li>
        <% if user_signed_in? %>
            <li>
              <%= link_to 'New Item', new_item_path %>
            </li>
            <li>
              <%= link_to 'Reservations', '/reservations' %>
            </li>
            <li>
              <%= link_to 'New Item Type', '/item_types' %>
            </li>
            <li>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
            </li>

        <% else %>
            <li>
              <%= link_to('Login', new_user_session_path) %>
            </li>
        <% end %>

      </ul>
    </div>
  </div>
  <!-- /.navbar-collapse -->
  <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!-- <!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Lendy" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Lendy" %>">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html> -->
<link href="https://fonts.googleapis.com/css?family=Lato|Raleway" rel="stylesheet">
<!DOCTYPE html>
<html>
<head>
  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
  <title>Example application with SimpleForm and Twitter Bootstrap</title>
  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/nav' %>
  <div class="container master-container">

    <% if notice %>
      <div class="alert alert-success fade in" data-alert="alert">
        <a class="close" data-dismiss='alert' href="#">×</a>
        <p><%= notice %></p>
      </div>
    <% end %>

    <%= yield %>
  </div>
  <%= javascript_include_tag "application" %>
</body>
</html>

app/views/layouts/grayscale.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lendy - Connecting Needs</title>
  <%= stylesheet_link_tag 'grayscale/manifest.css', media: 'all' %>
  <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <%= javascript_include_tag 'grayscale/manifest.js' %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

<%= yield %>

</body>
</html>